"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import oto2lab_gui

# Implementing MyFrame1
class MyProject1MyFrame1( oto2lab_gui.MyFrame1 ):
	def __init__( self, parent ):
		oto2lab_gui.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def m_dirPicker1OnDirChanged( self, event ):
		# TODO: Implement m_dirPicker1OnDirChanged
		pass

	def m_modeSelect1OnRadioBox( self, event ):
		# TODO: Implement m_modeSelect1OnRadioBox
		pass

	def m_displayConsole1OnCheckBox( self, event ):
		# TODO: Implement m_displayConsole1OnCheckBox
		pass

	def m_convertButton1OnButtonClick( self, event ):
		# TODO: Implement m_convertButton1OnButtonClick
		pass

	def m_filePicker1OnFileChanged( self, event ):
		# TODO: Implement m_filePicker1OnFileChanged
		pass

	def m_modeSelect2OnRadioBox( self, event ):
		# TODO: Implement m_modeSelect2OnRadioBox
		pass

	def m_displayConsole2OnCheckBox( self, event ):
		# TODO: Implement m_displayConsole2OnCheckBox
		pass

	def m_convertButton2OnButtonClick( self, event ):
		# TODO: Implement m_convertButton2OnButtonClick
		pass


